CC: [~lirui]

Looked through the travis log and the "various exceptions" are actually error logs printed by Hive code. Most of these logs are generated by negative test cases, so they're expected.

The actual failure was {{TableEnvHiveConnectorTest}} and it failed because it couldn't connect to metastore server. I'm not sure about the root cause at the moment. It could be just flaky network connections.
[~sewen] can the test failure be easily reproduced?

I did not try to reproduce it.
How can a flaky network connection be the cause? Isn't the test setup local?

Another thing is to clean up the test logging. All other code in Flink makes a good effort to not print test exceptions, expected failures, etc. to make log reading easier for debugging. Would be good if the Hive code improved there as well.


Hey [~sewen], yes the test is setup locally. It launches a separate metastore process and connects to it. Judging from the stacktrace, either the metastore process crashed shortly after it started, or we had some problem establishing the connection. The log of the metastore process is disabled by default to avoid flooding travis output. We can't tell the root cause for sure unless we reproduce the issue with metastore log enabled.

I'll see what I can do about the exception logs. I agree we should suppress them for negative test cases, while have them enabled for normal tests.

Not sure if it is related, but I found this ticket when searching for {{TableEnvHiveConnectorTest}}. I got the following test failures here: https://dev.azure.com/rmetzger/Flink/_build/results?buildId=5473&view=logs&j=2a16b520-7a96-573c-edfb-f1a66b90edcf&t=29adce53-ab37-528a-c7a0-fa6702b05b5e

{code}
[ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 51.722 s <<< FAILURE! - in org.apache.flink.connectors.hive.TableEnvHiveConnectorTest
[ERROR] testViews(org.apache.flink.connectors.hive.TableEnvHiveConnectorTest)  Time elapsed: 3.274 s  <<< FAILURE!
java.lang.AssertionError: Sql optimization: Assertion error: RelSubset [rel#1070:Subset#21.BATCH_PHYSICAL.any.[0 ASC-nulls-first]] does not contain its best RelNode [rel#1189:BatchExecSort.BATCH_PHYSICAL.hash[0]false.[0 ASC-nulls-first](input=RelSubset#1107,orderBy=key ASC)]
	at org.apache.flink.connectors.hive.TableEnvHiveConnectorTest.testViews(TableEnvHiveConnectorTest.java:505)
Caused by: java.lang.AssertionError: RelSubset [rel#1070:Subset#21.BATCH_PHYSICAL.any.[0 ASC-nulls-first]] does not contain its best RelNode [rel#1189:BatchExecSort.BATCH_PHYSICAL.hash[0]false.[0 ASC-nulls-first](input=RelSubset#1107,orderBy=key ASC)]
	at org.apache.flink.connectors.hive.TableEnvHiveConnectorTest.testViews(TableEnvHiveConnectorTest.java:505)
{code}

As well as 
{code}
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 33.605 s <<< FAILURE! - in org.apache.flink.connectors.hive.HiveTableSourceTest
[ERROR] testProjectionPushDown(org.apache.flink.connectors.hive.HiveTableSourceTest)  Time elapsed: 1.577 s  <<< FAILURE!
java.lang.AssertionError: Sql optimization: Assertion error: rel [rel#4123:BatchExecSort.BATCH_PHYSICAL.hash[0]true.[0 ASC-nulls-first](input=RelSubset#4122,orderBy=p1 ASC)] has lower cost {2.2854877458921212E8 rows, 1.0778652121441809E10 cpu, 2.0E9 io, 1.522601311424648E8 network, 6.894845442213011E9 memory} than best cost {2.475812909820202E8 rows, 1.298903194530267E10 cpu, 2.0E9 io, 3.045202622849296E8 network, 7.389690868426022E9 memory} of subset [rel#4045:Subset#5.BATCH_PHYSICAL.hash[0]true.[0 ASC-nulls-first]]
	at org.apache.flink.connectors.hive.HiveTableSourceTest.testProjectionPushDown(HiveTableSourceTest.java:339)
Caused by: java.lang.AssertionError: rel [rel#4123:BatchExecSort.BATCH_PHYSICAL.hash[0]true.[0 ASC-nulls-first](input=RelSubset#4122,orderBy=p1 ASC)] has lower cost {2.2854877458921212E8 rows, 1.0778652121441809E10 cpu, 2.0E9 io, 1.522601311424648E8 network, 6.894845442213011E9 memory} than best cost {2.475812909820202E8 rows, 1.298903194530267E10 cpu, 2.0E9 io, 3.045202622849296E8 network, 7.389690868426022E9 memory} of subset [rel#4045:Subset#5.BATCH_PHYSICAL.hash[0]true.[0 ASC-nulls-first]]
	at org.apache.flink.connectors.hive.HiveTableSourceTest.testProjectionPushDown(HiveTableSourceTest.java:339)
{code}

Are they related to this? If not, I can also file a separate ticket.

Hi [~rmetzger], I don't think the errors you pasted are related to this ticket. This ticket is about {{TableEnvHiveConnectorTest}} failing during setup, i.e. when launching metastore server, making connections, etc.
The errors you pasted are failures of specific queries, which I think might be caused by changes in the planner.

Okay, I filed a separate ticket here: https://issues.apache.org/jira/browse/FLINK-16256

[~sewen] I just noted FLINK-15672 has fixed the annoying error logs of the negative tests. It essentially disabled loggings of all the hive tests. While such error logs can be useful in case anything really goes wrong, I can live with that if it's following Flink convention.

The way to get error logs is to extend {{TestLogger}}. Then the logs go to real logs, not to standard out. The logs can be downloaded from failed builds, an instruction is usually given at the end of the build.

I think the test hasn't failed in recent builds. Perhaps we can deprioritize this ticket? It's hard to tell the root cause at this moment.
BTW, I have fixed an issue via FLINK-16196 which might be related.

I will close this for now since this hasn't reproduce for a long time and other suspicious issue which might related to this has been fixed.

